/**
 * GhostBrain Autonomous Swarm — Shared Types
 *
 * All swarm modules import from here.  Keeping types in one place avoids
 * circular dependencies across the swarm, agent-registry, controller, and
 * memory-sync modules.
 */

// ── Domains ───────────────────────────────────────────────────────────────────

export type SwarmDomain =
  | "infrastructure"  // container + VM repair, resource management
  | "blockchain"      // validator health, chain sync
  | "security"        // threat detection, access control
  | "devops"          // deployments, upgrades, CI/CD
  | "performance"     // resource optimisation, throughput
  | "recovery";       // failure recovery, self-healing

// ── Task ──────────────────────────────────────────────────────────────────────

export interface SwarmTask {
  /** UUID — auto-generated by the router when omitted. */
  id:          string;
  /** Raw event type string (e.g. "container_crash", "jailed_validator"). */
  type:        string;
  /** Domain inferred by the TaskRouter or supplied explicitly by the caller. */
  domain:      SwarmDomain;
  /** Structured task payload.  Never concatenated to a shell command. */
  data:        Record<string, unknown>;
  /** Who triggered this task, for the audit trail. */
  requestedBy: string;
  /** Unix epoch ms. */
  ts:          number;
  /** When true the handler simulates the action without side-effects. */
  dryRun?:     boolean;
}

// ── Result ────────────────────────────────────────────────────────────────────

export interface SwarmResult {
  taskId:     string;
  agentName:  string;
  domain:     SwarmDomain;
  ok:         boolean;
  detail:     string;
  executedAt: number;
  durationMs: number;
}

// ── Event ─────────────────────────────────────────────────────────────────────

export interface SwarmEvent {
  type:       string;
  domain:     SwarmDomain;
  severity:   "info" | "warn" | "critical";
  resourceId: string;
  payload:    Record<string, unknown>;
}

// ── Agent contract ────────────────────────────────────────────────────────────

/** Every swarm agent must implement this interface. */
export interface SwarmAgent {
  readonly name:   string;
  readonly domain: SwarmDomain;
  canHandle(task: SwarmTask): boolean;
  execute(task: SwarmTask): Promise<SwarmResult>;
  stats(): Record<string, unknown>;
}
