= GRC-721

[.readme-notice]
NOTE: This document is better viewed at https://docs.ghostchain.com/contracts/api/token/grc721

This set of interfaces, contracts, and utilities is all related to the https://eips.ghostchain.org/EIPS/eip-721[GRC-721 Non-Fungible Token Standard].

TIP: For a walk through on how to create an GRC-721 token read our xref:ROOT:grc721.adoc[GRC-721 guide].

The GRC specifies four interfaces:

* {IGRC721}: Core functionality required in all compliant implementation.
* {IGRC721Metadata}: Optional extension that adds name, symbol, and token URI, almost always included.
* {IGRC721Enumerable}: Optional extension that allows enumerating the tokens on chain, often not included since it requires large gas overhead.
* {IGRC721Receiver}: An interface that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`.

GhostChain Contracts provides implementations of all four interfaces:

* {GRC721}: The core and metadata extensions, with a base URI mechanism.
* {GRC721Enumerable}: The enumerable extension.
* {GRC721Holder}: A bare bones implementation of the receiver interface.

Additionally there are a few of other extensions:

* {GRC721Burnable}: A way for token holders to burn their own tokens.
* {GRC721Consecutive}: An implementation of https://eips.ghostchain.org/EIPS/eip-2309[GRC-2309] for minting batches of tokens during construction, in accordance with GRC-721.
* {GRC721Crosschain}: Embedded {BridgeNonFungible} bridge, making the token crosschain through the use of GRC-7786 gateways.
* {GRC721Pausable}: A primitive to pause contract operation.
* {GRC721Royalty}: A way to signal royalty information following GRC-2981.
* {GRC721URIStorage}: A more flexible but more expensive way of storing metadata.
* {GRC721Votes}: Support for voting and vote delegation.
* {GRC721Wrapper}: Wrapper to create an GRC-721 backed by another GRC-721, with deposit and withdraw methods. Useful in conjunction with {GRC721Votes}.

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in GRC-721 (such as <<GRC721-_mint-address-uint256-,`_mint`>>) and expose them as external functions in the way they prefer.

== Core

{{IGRC721}}

{{IGRC721Metadata}}

{{IGRC721Enumerable}}

{{GRC721}}

{{GRC721Enumerable}}

{{IGRC721Receiver}}

== Extensions

{{GRC721Burnable}}

{{GRC721Consecutive}}

{{GRC721Crosschain}}

{{GRC721Pausable}}

{{GRC721Royalty}}

{{GRC721URIStorage}}

{{GRC721Votes}}

{{GRC721Wrapper}}

== Utilities

{{GRC721Holder}}

{{GRC721Utils}}
