{
  "apiVersion": "apps/v1",
  "kind": "StatefulSet",
  "metadata": {
    "name": "l1-mainnet-geth",
    "labels": {
      "app": "l1-mainnet-geth",
      "role": "chain"
    },
    "annotations": {
      "ghost.source.compose": "/home/ghost/ghostl-stack/infra/docker/compose/docker-compose.core.yml",
      "ghost.no_recreate": "true"
    }
  },
  "spec": {
    "serviceName": "l1-mainnet-geth",
    "replicas": 1,
    "podManagementPolicy": "OrderedReady",
    "updateStrategy": {
      "type": "OnDelete"
    },
    "selector": {
      "matchLabels": {
        "app": "l1-mainnet-geth"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "l1-mainnet-geth",
          "role": "chain"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "l1-mainnet-geth",
            "image": "ethereum/client-go:stable",
            "command": null,
            "args": "--syncmode snap --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3,txpool --http.vhosts=\"*\" --http.corsdomain=\"*\" --ws --ws.addr=0.0.0.0 --ws.port=8546 --ws.api=eth,net,web3 --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=\"*\" --datadir=/data --cache=4096 --maxpeers=50 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060\n",
            "env": [],
            "ports": [
              {
                "containerPort": 8545,
                "protocol": "TCP"
              },
              {
                "containerPort": 8546,
                "protocol": "TCP"
              },
              {
                "containerPort": 8551,
                "protocol": "TCP"
              },
              {
                "containerPort": 6060,
                "protocol": "TCP"
              }
            ],
            "volumeMounts": [
              {
                "name": "l1-mainnet-geth-data",
                "mountPath": "/data"
              }
            ]
          }
        ]
      }
    },
    "volumeClaimTemplates": [
      {
        "metadata": {
          "name": "l1-mainnet-geth-data"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      }
    ]
  }
}
