{
  "apiVersion": "apps/v1",
  "kind": "StatefulSet",
  "metadata": {
    "name": "op-node",
    "labels": {
      "app": "op-node",
      "role": "chain"
    },
    "annotations": {
      "ghost.source.compose": "/home/ghost/ghostl-stack/infra/docker/compose/docker-compose.core.yml",
      "ghost.no_recreate": "true"
    }
  },
  "spec": {
    "serviceName": "op-node",
    "replicas": 1,
    "podManagementPolicy": "OrderedReady",
    "updateStrategy": {
      "type": "OnDelete"
    },
    "selector": {
      "matchLabels": {
        "app": "op-node"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "op-node",
          "role": "chain"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "op-node",
            "image": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:devnet",
            "command": null,
            "args": "op-node --l1=ws://l1:8546 --l1.beacon=http://l1-bn:5052 --l1.epoch-poll-interval=12s --l1.http-poll-interval=6s --l2=http://l2:8551 --l2.jwt-secret=/config/jwt-secret.txt --sequencer.enabled --sequencer.l1-confs=0 --verifier.l1-confs=0 --p2p.sequencer.key=8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba --rollup.config=/rollup.json --rpc.addr=0.0.0.0 --rpc.port=8545 --p2p.listen.ip=0.0.0.0 --p2p.listen.tcp=9003 --p2p.listen.udp=9003 --p2p.scoring.peers=light --p2p.ban.peers=true --p2p.priv.path=/config/p2p-node-key.txt --metrics.enabled --metrics.addr=0.0.0.0 --metrics.port=7300 --pprof.enabled --rpc.enable-admin --safedb.path=/db --altda.enabled=${ALTDA_ENABLED} --altda.da-service=${ALTDA_SERVICE} --altda.da-server=http://da-server:3100\n",
            "env": [],
            "ports": [
              {
                "containerPort": 8545,
                "protocol": "TCP"
              },
              {
                "containerPort": 9003,
                "protocol": "TCP"
              },
              {
                "containerPort": 7300,
                "protocol": "TCP"
              },
              {
                "containerPort": 6060,
                "protocol": "TCP"
              }
            ],
            "volumeMounts": [
              {
                "name": "safedb_data",
                "mountPath": "/db"
              },
              {
                "name": "${PWD}/p2p-sequencer-key.txt",
                "mountPath": "/config/p2p-sequencer-key.txt"
              },
              {
                "name": "${PWD}/p2p-node-key.txt",
                "mountPath": "/config/p2p-node-key.txt"
              },
              {
                "name": "${PWD}/test-jwt-secret.txt",
                "mountPath": "/config/jwt-secret.txt"
              },
              {
                "name": "${PWD}/../.devnet/rollup.json",
                "mountPath": "/rollup.json"
              },
              {
                "name": "op_log",
                "mountPath": "/op_log"
              }
            ]
          }
        ]
      }
    },
    "volumeClaimTemplates": [
      {
        "metadata": {
          "name": "safedb_data"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      },
      {
        "metadata": {
          "name": "${PWD}/p2p-sequencer-key.txt"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      },
      {
        "metadata": {
          "name": "${PWD}/p2p-node-key.txt"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      },
      {
        "metadata": {
          "name": "${PWD}/test-jwt-secret.txt"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      },
      {
        "metadata": {
          "name": "${PWD}/../.devnet/rollup.json"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      },
      {
        "metadata": {
          "name": "op_log"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      }
    ]
  }
}
