{
  "apiVersion": "apps/v1",
  "kind": "StatefulSet",
  "metadata": {
    "name": "postgres",
    "labels": {
      "app": "postgres",
      "role": "api"
    },
    "annotations": {
      "ghost.source.compose": "/home/ghost/ghostl-stack/infra/docker/compose/docker-compose.services.yml",
      "ghost.no_recreate": "false"
    }
  },
  "spec": {
    "serviceName": "postgres",
    "replicas": 1,
    "podManagementPolicy": "OrderedReady",
    "updateStrategy": {
      "type": "OnDelete"
    },
    "selector": {
      "matchLabels": {
        "app": "postgres"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "postgres",
          "role": "api"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "command": null,
            "args": null,
            "env": [
              {
                "name": "POSTGRES_DB",
                "value": "ghost_compliance"
              },
              {
                "name": "POSTGRES_PASSWORD",
                "value": "${POSTGRES_PASSWORD:-ghostpass}"
              },
              {
                "name": "POSTGRES_USER",
                "value": "ghost"
              }
            ],
            "ports": [
              {
                "containerPort": 5432,
                "protocol": "TCP"
              }
            ],
            "volumeMounts": [
              {
                "name": "pg_data",
                "mountPath": "/var/lib/postgresql/data"
              }
            ]
          }
        ]
      }
    },
    "volumeClaimTemplates": [
      {
        "metadata": {
          "name": "pg_data"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      }
    ]
  }
}
