{
  "apiVersion": "apps/v1",
  "kind": "StatefulSet",
  "metadata": {
    "name": "redis",
    "labels": {
      "app": "redis",
      "role": "api"
    },
    "annotations": {
      "ghost.source.compose": "/home/ghost/ghostl-stack/infra/docker/compose/docker-compose.services.yml",
      "ghost.no_recreate": "false"
    }
  },
  "spec": {
    "serviceName": "redis",
    "replicas": 1,
    "podManagementPolicy": "OrderedReady",
    "updateStrategy": {
      "type": "OnDelete"
    },
    "selector": {
      "matchLabels": {
        "app": "redis"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "redis",
          "role": "api"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "redis",
            "image": "redis:7-alpine",
            "command": null,
            "args": [
              "redis-server",
              "--appendonly",
              "yes"
            ],
            "env": [],
            "ports": [
              {
                "containerPort": 6379,
                "protocol": "TCP"
              }
            ],
            "volumeMounts": [
              {
                "name": "redis_data",
                "mountPath": "/data"
              }
            ]
          }
        ]
      }
    },
    "volumeClaimTemplates": [
      {
        "metadata": {
          "name": "redis_data"
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          }
        }
      }
    ]
  }
}
