'use client';

/**
 * GhostChain Protocol Evolution Dashboard (Phases 71-82)
 *
 * Displays the live state of the Autonomous Protocol Evolution Engine:
 *   - Current engine phase (idle / analyzing / simulating / proposing / submitting)
 *   - Analysis cycle statistics
 *   - Recent improvement detections
 *   - Governance proposals with Approve / Reject (no auto-execute)
 *
 * Data: polls /api/evolution/status every 15 s.
 *
 * GOVERNANCE MODEL:
 *   All proposals generated by APE are forwarded to the signing relay.
 *   Validators must vote to approve — the engine never deploys autonomously.
 */

import { useEffect, useState } from 'react';

// ── Types ─────────────────────────────────────────────────────────────────────

type EnginePhase = 'idle' | 'analyzing' | 'simulating' | 'proposing' | 'submitting';
type RiskLevel   = 'low' | 'medium' | 'high';
type ProposalStatus = 'pending' | 'submitted' | 'submit_failed';

interface AnalysisResult {
  improvementDetected: boolean;
  type?: string;
  source:  string;
  value?:  number;
  detail:  string;
  ts:      string;
}

interface EvolutionProposal {
  id:                        string;
  title:                     string;
  description:               string;
  type:                      string;
  estimatedImprovementPct:   number;
  riskLevel:                 RiskLevel;
  simulationId:              string;
  triggerValue?:             number;
  status:                    ProposalStatus;
  createdAt:                 string;
}

interface EngineRules {
  maxBlockTimeMs:               number;
  targetGasUsagePct:            number;
  validatorBalanceThresholdPct: number;
  cycleIntervalMs:              number;
  maxProposalsPerDay:           number;
}

interface EvolutionStatus {
  phase:                EnginePhase;
  cycleCount:           number;
  improvementsDetected: number;
  simulationsRun:       number;
  proposalsGenerated:   number;
  proposalsSubmitted:   number;
  proposalsFailed:      number;
  lastCycleAt:          string | null;
  recentProposals:      EvolutionProposal[];
  recentAnalyses:       AnalysisResult[];
  rules?:               EngineRules;
  ts:                   string;
  error?:               string;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const RISK_COLOR: Record<RiskLevel, string> = {
  low:    '#22c55e',
  medium: '#f59e0b',
  high:   '#ef4444',
};

const PHASE_LABEL: Record<EnginePhase, string> = {
  idle:       '● Idle',
  analyzing:  '◎ Analyzing',
  simulating: '⟳ Simulating',
  proposing:  '✎ Generating Proposal',
  submitting: '↑ Submitting',
};

const PHASE_COLOR: Record<EnginePhase, string> = {
  idle:       '#6b7280',
  analyzing:  '#3b82f6',
  simulating: '#a855f7',
  proposing:  '#f59e0b',
  submitting: '#22c55e',
};

const POLL_MS = 15_000;

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtTime(iso: string | null): string {
  if (!iso) return 'never';
  try { return new Date(iso).toLocaleTimeString(); } catch { return iso; }
}

// ── Sub-components ─────────────────────────────────────────────────────────────

function StatBox({ label, value, color }: { label: string; value: string | number; color?: string }) {
  return (
    <div style={{ background: '#111827', border: '1px solid #1e1e2e', borderRadius: 8, padding: '10px 16px' }}>
      <div style={{ fontSize: 9, color: '#6b7280', textTransform: 'uppercase', marginBottom: 3 }}>{label}</div>
      <div style={{ fontSize: 20, fontWeight: 700, fontFamily: 'monospace', color: color ?? '#e2e8f0' }}>{value}</div>
    </div>
  );
}

function AnalysisRow({ a }: { a: AnalysisResult }) {
  const color = a.improvementDetected ? '#f59e0b' : '#22c55e';
  return (
    <div style={{ background: '#111827', border: `1px solid ${color}33`, borderRadius: 6, padding: '8px 12px', marginBottom: 6, fontSize: 12 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 2 }}>
        <span style={{ color, fontWeight: 600 }}>
          {a.improvementDetected ? `⚠ ${a.type ?? 'improvement'}` : `✓ ${a.source}`}
        </span>
        <span style={{ color: '#6b7280' }}>{fmtTime(a.ts)}</span>
      </div>
      <div style={{ color: '#d1d5db' }}>{a.detail}</div>
      {a.value !== undefined && <div style={{ color: '#6b7280', marginTop: 2 }}>value: {a.value.toFixed(2)}</div>}
    </div>
  );
}

function ProposalCard({
  proposal,
  onApprove,
  onReject,
  actionState,
}: {
  proposal: EvolutionProposal;
  onApprove: (id: string) => void;
  onReject:  (id: string) => void;
  actionState: 'idle' | 'approving' | 'rejecting' | 'approved' | 'rejected';
}) {
  const riskColor = RISK_COLOR[proposal.riskLevel] ?? '#6b7280';

  return (
    <div style={{
      background: '#111827',
      border: `1px solid ${riskColor}44`,
      borderRadius: 8, padding: '14px 16px', marginBottom: 10,
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
        <span style={{ fontSize: 11, color: '#6b7280', fontFamily: 'monospace' }}>{proposal.id.slice(0, 8)}</span>
        <div style={{ display: 'flex', gap: 8 }}>
          <span style={{ fontSize: 11, padding: '2px 7px', borderRadius: 4, background: `${riskColor}22`, color: riskColor }}>
            {proposal.riskLevel} risk
          </span>
          <span style={{ fontSize: 11, color: '#4b5563' }}>{fmtTime(proposal.createdAt)}</span>
        </div>
      </div>

      <div style={{ fontWeight: 700, color: '#f1f5f9', fontSize: 14, marginBottom: 4 }}>{proposal.title}</div>

      <pre style={{
        fontSize: 11, color: '#94a3b8', whiteSpace: 'pre-wrap', wordBreak: 'break-word',
        background: '#0f172a', borderRadius: 4, padding: '8px 10px', margin: '6px 0 10px',
      }}>
        {proposal.description}
      </pre>

      <div style={{ display: 'flex', gap: 16, fontSize: 12, color: '#6b7280', marginBottom: 10 }}>
        <span>est. improvement: <strong style={{ color: '#22c55e' }}>+{proposal.estimatedImprovementPct}%</strong></span>
        <span>simulation: <span style={{ fontFamily: 'monospace' }}>{proposal.simulationId.slice(0, 8)}</span></span>
      </div>

      {proposal.status === 'submitted' && (
        <div style={{ color: '#22c55e', fontSize: 12, fontWeight: 600 }}>
          ✓ Forwarded to signing relay — awaiting governance vote
        </div>
      )}
      {proposal.status === 'submit_failed' && (
        <div style={{ color: '#ef4444', fontSize: 12 }}>✗ Submission failed — signing relay unreachable</div>
      )}

      {actionState === 'approved' && (
        <div style={{ color: '#22c55e', fontSize: 12, fontWeight: 600 }}>✓ Approved — forwarded to signing relay</div>
      )}
      {actionState === 'rejected' && (
        <div style={{ color: '#ef4444', fontSize: 12 }}>✗ Rejected</div>
      )}

      {(actionState === 'idle' || actionState === 'approving' || actionState === 'rejecting') &&
       proposal.status === 'pending' && (
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            onClick={() => onApprove(proposal.id)}
            disabled={actionState !== 'idle'}
            style={{
              padding: '5px 14px', fontSize: 12, borderRadius: 4, border: 'none', cursor: 'pointer',
              background: '#16a34a', color: '#fff', fontWeight: 600,
              opacity: actionState !== 'idle' ? 0.5 : 1,
            }}
          >
            {actionState === 'approving' ? 'Forwarding…' : 'Approve'}
          </button>
          <button
            onClick={() => onReject(proposal.id)}
            disabled={actionState !== 'idle'}
            style={{
              padding: '5px 14px', fontSize: 12, borderRadius: 4, border: '1px solid #374151',
              cursor: 'pointer', background: 'transparent', color: '#9ca3af',
              opacity: actionState !== 'idle' ? 0.5 : 1,
            }}
          >
            Reject
          </button>
        </div>
      )}
    </div>
  );
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function EvolutionPage() {
  const [status, setStatus]           = useState<EvolutionStatus | null>(null);
  const [loading, setLoading]         = useState(true);
  const [activeTab, setActiveTab]     = useState<'overview' | 'analyses' | 'proposals'>('overview');
  const [proposalActions, setProposalActions] = useState<Record<string, 'idle' | 'approving' | 'rejecting' | 'approved' | 'rejected'>>({});

  const fetchStatus = async () => {
    try {
      const r = await fetch('/api/evolution/status', { cache: 'no-store' });
      const data = await r.json() as EvolutionStatus;
      setStatus(data);
    } catch { /* keep last state */ }
    finally { setLoading(false); }
  };

  useEffect(() => {
    void fetchStatus();
    const t = setInterval(fetchStatus, POLL_MS);
    return () => clearInterval(t);
  }, []);

  const handleApprove = async (id: string) => {
    setProposalActions((p) => ({ ...p, [id]: 'approving' }));
    try {
      await fetch('/api/hyperghost', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ proposalId: id, action: 'approve', source: 'evolution' }),
      });
      setProposalActions((p) => ({ ...p, [id]: 'approved' }));
    } catch {
      setProposalActions((p) => ({ ...p, [id]: 'idle' }));
    }
  };

  const handleReject = (id: string) => {
    setProposalActions((p) => ({ ...p, [id]: 'rejected' }));
  };

  const s = status;
  const phase = s?.phase ?? 'idle';

  return (
    <div style={{ padding: 24, maxWidth: 1100, margin: '0 auto', color: '#e2e8f0', fontFamily: 'sans-serif' }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: '#f8fafc' }}>
          ⟳ GhostChain Protocol Evolution
        </h1>
        <div style={{ fontSize: 12, color: '#6b7280', marginTop: 4 }}>
          Autonomous Protocol Evolution Engine (APE) — proposals require governance ratification
          {s?.ts && <span style={{ marginLeft: 12 }}>updated {fmtTime(s.ts)}</span>}
        </div>
      </div>

      {/* Offline banner */}
      {s?.error && (
        <div style={{ background: '#1c0f00', border: '1px solid #78350f', borderRadius: 6, padding: '8px 14px', marginBottom: 16, fontSize: 12, color: '#fbbf24' }}>
          ⚠ Evolution engine offline — showing last known state
        </div>
      )}

      {/* Engine phase badge */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <div style={{
          padding: '6px 14px', borderRadius: 20, fontSize: 13, fontWeight: 600,
          background: `${PHASE_COLOR[phase]}22`, color: PHASE_COLOR[phase],
          border: `1px solid ${PHASE_COLOR[phase]}44`,
        }}>
          {PHASE_LABEL[phase]}
        </div>
        {s?.lastCycleAt && (
          <span style={{ fontSize: 12, color: '#6b7280' }}>last cycle: {fmtTime(s.lastCycleAt)}</span>
        )}
      </div>

      {/* Stats */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6,1fr)', gap: 10, marginBottom: 24 }}>
        <StatBox label="Analysis Cycles"         value={loading ? '…' : s?.cycleCount ?? 0} />
        <StatBox label="Improvements Found"      value={s?.improvementsDetected ?? 0} color="#f59e0b" />
        <StatBox label="Simulations Run"         value={s?.simulationsRun ?? 0}      color="#a855f7" />
        <StatBox label="Proposals Generated"     value={s?.proposalsGenerated ?? 0}  color="#3b82f6" />
        <StatBox label="Proposals Submitted"     value={s?.proposalsSubmitted ?? 0}  color="#22c55e" />
        <StatBox label="Submit Failures"         value={s?.proposalsFailed ?? 0}     color={s?.proposalsFailed ? '#ef4444' : '#6b7280'} />
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 16, borderBottom: '1px solid #1e293b' }}>
        {(['overview', 'analyses', 'proposals'] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              padding: '7px 16px', fontSize: 13, border: 'none', borderRadius: '4px 4px 0 0', cursor: 'pointer',
              background: activeTab === tab ? '#1e293b' : 'transparent',
              color: activeTab === tab ? '#f1f5f9' : '#6b7280',
              fontWeight: activeTab === tab ? 600 : 400,
            }}
          >
            {tab === 'overview'   && 'Evolution Rules'}
            {tab === 'analyses'   && `Analyses (${s?.recentAnalyses.length ?? 0})`}
            {tab === 'proposals'  && `Proposals (${s?.recentProposals.length ?? 0})`}
          </button>
        ))}
      </div>

      {/* Overview tab — show current rule thresholds */}
      {activeTab === 'overview' && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <div style={{ background: '#111827', border: '1px solid #1e1e2e', borderRadius: 8, padding: 16 }}>
            <div style={{ fontWeight: 600, marginBottom: 10, color: '#94a3b8' }}>Detection Thresholds</div>
            <div style={{ fontSize: 13, color: '#d1d5db', lineHeight: 1.8 }}>
              <div>Max block time: <strong style={{ color: '#f1f5f9' }}>{s?.rules?.maxBlockTimeMs ?? POLL_MS}ms</strong></div>
              <div>Target gas usage: <strong style={{ color: '#f1f5f9' }}>{s?.rules?.targetGasUsagePct ?? 60}%</strong></div>
              <div>Validator balance delta: <strong style={{ color: '#f1f5f9' }}>{s?.rules?.validatorBalanceThresholdPct ?? 20}%</strong></div>
            </div>
          </div>
          <div style={{ background: '#111827', border: '1px solid #1e1e2e', borderRadius: 8, padding: 16 }}>
            <div style={{ fontWeight: 600, marginBottom: 10, color: '#94a3b8' }}>Safety Guards</div>
            <div style={{ fontSize: 13, color: '#d1d5db', lineHeight: 1.8 }}>
              <div>Cycle interval: <strong style={{ color: '#f1f5f9' }}>{((s?.rules?.cycleIntervalMs ?? 60_000) / 1_000).toFixed(0)}s</strong></div>
              <div>Max proposals/day: <strong style={{ color: '#f1f5f9' }}>{s?.rules?.maxProposalsPerDay ?? 5}</strong></div>
              <div>Deployment: <strong style={{ color: '#22c55e' }}>Human governance vote required</strong></div>
              <div>Auto-execute: <strong style={{ color: '#ef4444' }}>Disabled</strong></div>
            </div>
          </div>

          {/* Upgrade flow diagram */}
          <div style={{ gridColumn: '1/-1', background: '#111827', border: '1px solid #1e1e2e', borderRadius: 8, padding: 16 }}>
            <div style={{ fontWeight: 600, marginBottom: 12, color: '#94a3b8' }}>Upgrade Flow</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap', fontSize: 12 }}>
              {[
                ['AI detects inefficiency', '#3b82f6'],
                ['→', '#4b5563'],
                ['Protocol simulation', '#a855f7'],
                ['→', '#4b5563'],
                ['Sandbox test', '#f59e0b'],
                ['→', '#4b5563'],
                ['Proposal generated', '#f59e0b'],
                ['→', '#4b5563'],
                ['Signing relay :7910', '#22c55e'],
                ['→', '#4b5563'],
                ['Validators vote', '#22c55e'],
                ['→', '#4b5563'],
                ['Upgrade deployed', '#22c55e'],
              ].map(([label, color], i) => (
                <span key={i} style={{ color, fontWeight: label === '→' ? 400 : 600 }}>{label}</span>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Analyses tab */}
      {activeTab === 'analyses' && (
        <div>
          {(s?.recentAnalyses ?? []).length === 0 ? (
            <div style={{ color: '#4b5563' }}>No analysis data yet — wait for first cycle.</div>
          ) : (
            (s?.recentAnalyses ?? []).map((a, i) => <AnalysisRow key={i} a={a} />)
          )}
        </div>
      )}

      {/* Proposals tab */}
      {activeTab === 'proposals' && (
        <div>
          <div style={{ fontSize: 12, color: '#6b7280', marginBottom: 12 }}>
            Proposals require human governance approval before any protocol change is deployed.
          </div>
          {(s?.recentProposals ?? []).length === 0 ? (
            <div style={{ color: '#4b5563' }}>No proposals generated yet.</div>
          ) : (
            (s?.recentProposals ?? []).map((p) => (
              <ProposalCard
                key={p.id}
                proposal={p}
                onApprove={handleApprove}
                onReject={handleReject}
                actionState={proposalActions[p.id] ?? 'idle'}
              />
            ))
          )}
        </div>
      )}
    </div>
  );
}
