[profile.default]
src = "contracts"
out = "contracts/out"
libs = [
  "optimism/packages/contracts-bedrock/lib",
  "optimism/packages/contracts-bedrock",
]
fs_permissions = [
  { access = "read", path = "optimism/packages/contracts-bedrock" }
]
remappings = [
  "@eth-optimism-bedrock/=optimism/packages/contracts-bedrock/",
  "@openzeppelin/=optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/",
  "@openzeppelin/contracts-upgradeable/=optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts/",
  "forge-std/=optimism/packages/contracts-bedrock/lib/forge-std/src/",
]
