/**
 * GhostExecutor AI
 *
 * Writes and deploys code: generates smart contracts via ghost-contract-factory,
 * triggers ghost-deployer for on-chain deployment, and integrates new modules.
 * Second agent in the upgrade-cycle workflow.
 */

import { fetch }      from "undici";
import { BaseAgent }  from "./base.js";
import type { SwarmTask } from "../types.js";

const CONTRACT_FACTORY_URL = process.env.CONTRACT_FACTORY_URL ?? "http://127.0.0.1:7985";
const DEPLOYER_URL         = process.env.DEPLOYER_URL          ?? "http://127.0.0.1:7961";

export class GhostExecutorAgent extends BaseAgent {
  readonly role         = "executor" as const;
  readonly name         = "GhostExecutor AI";
  readonly description  = "Writes and deploys smart contracts and services";
  readonly capabilities = [
    "generate-code", "deploy-contract", "upgrade-infrastructure",
    "integrate-modules", "service-deployment",
  ];

  protected async handleTask(task: SwarmTask): Promise<Record<string, unknown>> {
    switch (task.type) {
      case "generate-code":    return this.generateCode(task.payload);
      case "deploy-contract":  return this.deployContract(task.payload);
      default:                 return this.generateCode(task.payload);
    }
  }

  private async generateCode(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
    const contractType = (payload["contractType"] as string | undefined) ?? "token";
    const name         = (payload["name"]         as string | undefined) ?? "GhostModule";

    // Try ghost-contract-factory (port 7985)
    try {
      const ctrl = new AbortController();
      setTimeout(() => ctrl.abort(), 10_000);
      const res  = await fetch(`${CONTRACT_FACTORY_URL}/generate`, {
        method:  "POST",
        headers: { "content-type": "application/json" },
        body:    JSON.stringify({ type: contractType, name, options: payload["options"] ?? {} }),
        signal:  ctrl.signal,
      });
      if (res.ok) {
        const data = await res.json() as Record<string, unknown>;
        return { source: "ghost-contract-factory", ...data };
      }
    } catch {
      // factory not running — generate placeholder
    }

    // Offline fallback — deterministic code skeleton
    return {
      source:   "offline-template",
      name,
      type:     contractType,
      solidity: `// GhostChain Contracts v5.6.1 (generated/${name}.sol)
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { GhostBrand } from "../ghost/GhostBrand.sol";

/// @title ${name}
/// @notice Auto-generated by GhostExecutor AI
contract ${name} is GhostBrand {
    address public immutable GOVERNANCE;
    constructor(address governance) { GOVERNANCE = governance; }
}`,
      status: "generated",
      requiresAudit: true,
    };
  }

  private async deployContract(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
    const contractName = (payload["contractName"] as string | undefined) ?? "Unknown";
    const targetLayer  = (payload["targetLayer"]  as string | undefined) ?? "L3";

    // Call ghost-deployer
    try {
      const ctrl = new AbortController();
      setTimeout(() => ctrl.abort(), 15_000);
      const res = await fetch(`${DEPLOYER_URL}/deploy`, {
        method:  "POST",
        headers: { "content-type": "application/json" },
        body:    JSON.stringify({ contractName, targetLayer, ...payload }),
        signal:  ctrl.signal,
      });
      if (res.ok) {
        const data = await res.json() as Record<string, unknown>;
        return { deployed: true, deployer: "ghost-deployer", ...data };
      }
    } catch {
      // Deployer offline
    }

    return {
      deployed:    false,
      contractName,
      targetLayer,
      status:      "queued",
      note:        "ghost-deployer offline — deployment queued for retry",
    };
  }
}
