table inet ghostnetsync_runtime {
  chain forward {
    type filter hook forward priority 0;
    policy accept;

    ct state established,related accept

    iifname "br-3a47f74c6888" oifname "br-315cdb4e43c9" accept
    iifname "br-315cdb4e43c9" oifname "br-fdf77c072ffa" accept

    iifname "br-3a47f74c6888" oifname "br-fdf77c072ffa" drop
    iifname "br-3a47f74c6888" oifname "enp2s0" drop

    iifname "br-315cdb4e43c9" oifname "enp2s0" drop
  }
}
