global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    cluster: ghoststack-hypervisor

scrape_configs:
  - job_name: "ghoststack-supervisor"
    static_configs:
      - targets: ["ghoststack-supervisor:9108"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "ghoststack-hypervisor"
