= GRC-1155

[.readme-notice]
NOTE: This document is better viewed at https://docs.ghostchain.com/contracts/api/token/grc1155

This set of interfaces and contracts are all related to the https://eips.ghostchain.org/EIPS/eip-1155[GRC-1155 Multi Token Standard].

The GRC consists of three interfaces which fulfill different roles, found here as {IGRC1155}, {IGRC1155MetadataURI} and {IGRC1155Receiver}.

{GRC1155} implements the mandatory {IGRC1155} interface, as well as the optional extension {IGRC1155MetadataURI}, by relying on the substitution mechanism to use the same URI for all token types, dramatically reducing gas costs.

Additionally there are multiple custom extensions, including:

* designation of addresses that can pause token transfers for all users ({GRC1155Pausable}).
* destruction of own tokens ({GRC1155Burnable}).
* crosschain bridging of tokens through GRC-7786 gateways ({GRC1155Crosschain}).

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in GRC-1155 (such as <<GRC1155-_mint-address-uint256-uint256-bytes-,`_mint`>>) and expose them as external functions in the way they prefer.

== Core

{{IGRC1155}}

{{IGRC1155MetadataURI}}

{{GRC1155}}

{{IGRC1155Receiver}}

== Extensions

{{GRC1155Burnable}}

{{GRC1155Crosschain}}

{{GRC1155Pausable}}

{{GRC1155Supply}}

{{GRC1155URIStorage}}

== Utilities

{{GRC1155Holder}}

{{GRC1155Utils}}
