/**
 * sdk-sync.ts — SDK wrapper generator.
 *
 * Generates TypeScript SDK wrapper classes for deployed GhostChain contracts.
 * These wrappers provide typed, ghost-SDK-native access to contract methods.
 */

export interface SdkWrapperOptions {
  /** Contract name, e.g. "GhostGovToken" */
  contractName: string;
  /** Deployed contract address expression (can be a placeholder) */
  address?: string;
  /** Subset of ABI methods to expose in the wrapper (omit for common GRC-20 methods) */
  methods?: SdkMethod[];
}

export interface SdkMethod {
  name: string;
  /** Solidity-style parameter list, e.g. "address to, uint256 amount" */
  params: string;
  /** TypeScript return type, e.g. "Promise<bigint>" */
  returnType: string;
  /** Whether the method mutates state (false = view/pure) */
  mutable: boolean;
  /** Short description for the JSDoc comment */
  description?: string;
}

/** Default GRC-20 methods included in all token wrappers */
const GRC20_METHODS: SdkMethod[] = [
  {
    name: "transfer",
    params: "to: string, amount: bigint",
    returnType: "Promise<boolean>",
    mutable: true,
    description: "Transfers tokens to the recipient.",
  },
  {
    name: "approve",
    params: "spender: string, amount: bigint",
    returnType: "Promise<boolean>",
    mutable: true,
    description: "Approves a spender to use tokens.",
  },
  {
    name: "balanceOf",
    params: "account: string",
    returnType: "Promise<bigint>",
    mutable: false,
    description: "Returns the token balance of an account.",
  },
  {
    name: "totalSupply",
    params: "",
    returnType: "Promise<bigint>",
    mutable: false,
    description: "Returns the total token supply.",
  },
];

/**
 * Generates a TypeScript SDK wrapper source string for a GhostChain contract.
 *
 * @param opts       Wrapper options
 * @param outputPath Workspace-relative destination path for the header comment.
 */
export function generateSdkWrapper(opts: SdkWrapperOptions, outputPath: string): string {
  const name    = opts.contractName;
  const address = opts.address ?? `process.env.${name.toUpperCase()}_ADDRESS ?? ""`;
  const methods = opts.methods ?? GRC20_METHODS;

  const methodBlocks = methods.map((m) => {
    const doc = m.description ? `  /** ${m.description} */\n` : "";
    const body = m.mutable
      ? `    const tx = await this._contract.${m.name}(${buildCallArgs(m.params)});\n    return tx !== undefined;`
      : `    return this._contract.${m.name}(${buildCallArgs(m.params)}) as ${m.returnType};`;
    return `${doc}  async ${m.name}(${m.params}): ${m.returnType} {\n${body}\n  }`;
  });

  return `\
// ${outputPath}
// GhostChain SDK wrapper — auto-generated by ghost-contract-factory

/**
 * ${name}Wrapper — Ghost SDK native wrapper for the ${name} contract.
 *
 * Uses hre.ghost (or any ghost-sdk provider) to interact with the deployed contract.
 * All amounts are in GhostWei (1 GST = 1e18 GhostWei).
 */
export class ${name}Wrapper {
  private readonly _address: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private readonly _contract: any;

  constructor(contract: unknown, address: string) {
    this._contract = contract;
    this._address  = address;
  }

  get address(): string {
    return this._address;
  }

  // ── Static factory ─────────────────────────────────────────────────────────

  /** Attaches to a deployed ${name} using hre.ghost. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  static async attach(ghost: any, at?: string): Promise<${name}Wrapper> {
    const addr     = at ?? ${address};
    const contract = await ghost.getContractAt("${name}", addr);
    return new ${name}Wrapper(contract, addr);
  }

  // ── Methods ───────────────────────────────────────────────────────────────

${methodBlocks.join("\n\n")}
}
`;
}

function buildCallArgs(paramStr: string): string {
  if (!paramStr.trim()) return "";
  return paramStr
    .split(",")
    .map((p) => p.trim().split(/\s+/).pop() ?? "")
    .join(", ");
}
