/**
 * ModuleGenerator — automatically creates missing Ghost module skeletons.
 */
import * as fs   from "fs";
import * as path from "path";

export class ModuleGenerator {
  generate(name: string): string {
    return `/**
 * ${name} — auto-generated by GhostCode AI.
 * Implement this module to complete the GhostStack ecosystem.
 */
export class ${name} {
  constructor() {
    // TODO: implement ${name}
  }

  run(): void {
    // TODO: implement run logic
  }
}
`;
  }

  /** Creates a file at `filePath` if it does not already exist. */
  createIfMissing(filePath: string, className: string): boolean {
    if (fs.existsSync(filePath)) return false;

    const dir = path.dirname(filePath);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, this.generate(className), "utf8");
    return true;
  }
}
