{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "ghost-registry",
    "labels": {
      "app": "ghost-registry",
      "role": "api"
    },
    "annotations": {
      "ghost.source.compose": "/home/ghost/ghostl-stack/infra/docker/compose/docker-compose.services.yml",
      "ghost.no_recreate": "false"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "ghost-registry"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "ghost-registry",
          "role": "api"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "ghost-registry",
            "image": "ghostl/ghost-registry:local",
            "command": null,
            "args": null,
            "env": [
              {
                "name": "PORT",
                "value": "8088"
              }
            ],
            "ports": [
              {
                "containerPort": 8088,
                "protocol": "TCP"
              }
            ],
            "volumeMounts": []
          }
        ]
      }
    }
  }
}
