import client from 'prom-client';

export type Metrics = {
  registry: client.Registry;

  uptimeSeconds: client.Gauge<string>;
  incidentsOpen: client.Gauge<'env' | 'scope' | 'severity'>;
  proposalsTotal: client.Gauge<'env' | 'status'>;
  patchSuggestionsTotal: client.Counter<'env' | 'scope'>;
  riskScore: client.Gauge<string>;
  gateState: client.Gauge<'env' | 'gate'>;
  probeLatencyMs: client.Histogram<'probe'>;
  probeFailuresTotal: client.Counter<'probe' | 'reason'>;
};

export function createMetrics(): Metrics {
  const registry = new client.Registry();
  client.collectDefaultMetrics({ register: registry });

  const uptimeSeconds = new client.Gauge({
    name: 'hyperghost_uptime_seconds',
    help: 'Service uptime in seconds',
    registers: [registry]
  });

  const incidentsOpen = new client.Gauge({
    name: 'hyperghost_incidents_open_total',
    help: 'Open incidents by env, scope and severity',
    labelNames: ['env', 'scope', 'severity'] as const,
    registers: [registry]
  });

  const proposalsTotal = new client.Gauge({
    name: 'hyperghost_proposals_total',
    help: 'Proposals by env and status',
    labelNames: ['env', 'status'] as const,
    registers: [registry]
  });

  const patchSuggestionsTotal = new client.Counter({
    name: 'hyperghost_patch_suggestions_total',
    help: 'Total patch suggestions generated by env and scope',
    labelNames: ['env', 'scope'] as const,
    registers: [registry]
  });

  const riskScore = new client.Gauge({
    name: 'hyperghost_risk_score',
    help: 'Latest computed supervisor risk score (0-100)',
    registers: [registry]
  });

  const gateState = new client.Gauge({
    name: 'hyperghost_gate_state',
    help: 'Gate enabled state (1 enabled, 0 disabled)',
    labelNames: ['env', 'gate'] as const,
    registers: [registry]
  });

  const probeLatencyMs = new client.Histogram({
    name: 'hyperghost_probe_latency_ms',
    help: 'Probe latency in milliseconds',
    labelNames: ['probe'] as const,
    buckets: [25, 50, 100, 250, 500, 1000, 2000, 5000, 10000],
    registers: [registry]
  });

  const probeFailuresTotal = new client.Counter({
    name: 'hyperghost_probe_failures_total',
    help: 'Probe failures by probe and reason',
    labelNames: ['probe', 'reason'] as const,
    registers: [registry]
  });

  return {
    registry,
    uptimeSeconds,
    incidentsOpen,
    proposalsTotal,
    patchSuggestionsTotal,
    riskScore,
    gateState,
    probeLatencyMs,
    probeFailuresTotal
  };
}

