[profile.default]
src = "src"
test = "test/foundry"
out = ".foundry-out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
cache_path = ".foundry-cache"
fuzz = { runs = 128 }
invariant = { runs = 64 }
