import Link from "next/link";
import { notFound } from "next/navigation";
import { GhostFooter, Ghostnavbar, StatusDot } from "@ghostchain/ui-components";

const NAV = [
  { label: "Dashboard", href: "/" },
  { label: "Models", href: "/models" },
  { label: "Alerts", href: "/alerts" },
  { label: "Proposals", href: "/proposals" },
];

type GhostBrainPage = {
  title: string;
  intro: string;
  cta: { label: string; href: string };
  rows: Array<{ name: string; detail: string; status: "healthy" | "degraded" }>;
  note: string;
};

const PAGES: Record<string, GhostBrainPage> = {
  models: {
    title: "GhostBrain Models",
    intro: "Inspect the branded AI fleet that classifies transactions, predicts congestion, and drafts governance proposals.",
    cta: { label: "Review alert posture", href: "/alerts" },
    rows: [
      { name: "Risk Engine", detail: "Scores GST movement, fraud signals, and contract activity across L1/L2/L3.", status: "healthy" },
      { name: "Load Predictor", detail: "Forecasts RPC pressure, queue backlog, and validator saturation before incidents emerge.", status: "healthy" },
      { name: "Governance Drafter", detail: "Prepares proposal language while preserving human ratification requirements.", status: "degraded" },
    ],
    note: "GhostBrain may draft and classify, but governance quorum remains mandatory before execution.",
  },
  alerts: {
    title: "AI Alerts",
    intro: "Track GhostBrain incidents across routing, validator health, congestion, and bridge safety.",
    cta: { label: "Inspect active proposals", href: "/proposals" },
    rows: [
      { name: "Routing Guard", detail: "Flags attempts to bypass the L3 -> L2 -> L1 settlement path.", status: "healthy" },
      { name: "Validator Risk", detail: "Surfaces missed blocks, restart churn, and slashing-adjacent behavior.", status: "degraded" },
      { name: "Gas Anomalies", detail: "Detects fee spikes and ghost_ RPC degradation before user-visible failures.", status: "degraded" },
    ],
    note: "Alerts should always explain the affected chain layer, confidence, and the recommended bounded action.",
  },
  proposals: {
    title: "AI-Drafted Proposals",
    intro: "Review candidate governance packages generated by GhostBrain for ratification by GhostChain governance.",
    cta: { label: "Return to GhostBrain dashboard", href: "/" },
    rows: [
      { name: "RPC Capacity Increase", detail: "Scale Ghost RPC ingress and rotate stressed endpoints without changing routing law.", status: "healthy" },
      { name: "Treasury Efficiency Review", detail: "Rebalance GST allocation reporting and archive evidence before quorum review.", status: "degraded" },
      { name: "Validator Recovery Drill", detail: "Exercise controlled failover playbooks and document restart cooldown behavior.", status: "healthy" },
    ],
    note: "AI can recommend and draft. It must not change consensus, supply, or bridge quorum without governance ratification.",
  },
};

export const dynamicParams = false;

export function generateStaticParams() {
  return Object.keys(PAGES).map((slug) => ({ slug: [slug] }));
}

export default async function GhostBrainSubpage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const page = PAGES[slug.join("/")];
  if (!page) notFound();

  return (
    <>
      <Ghostnavbar appName="GhostBrain" nav={NAV} />
      <main className="flex-1 max-w-5xl mx-auto px-4 sm:px-6 py-12 w-full">
        <div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-violet-400 mb-2">GhostBrain</p>
            <h1 className="text-3xl font-bold text-zinc-100 mb-2">{page.title}</h1>
            <p className="text-sm text-zinc-400 max-w-2xl">{page.intro}</p>
          </div>
          <Link href={page.cta.href} className="px-4 py-2.5 rounded-xl border border-zinc-700 bg-zinc-900 text-sm text-zinc-100 hover:bg-zinc-800 transition-colors">
            {page.cta.label}
          </Link>
        </div>

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-2 mb-8">
          {page.rows.map((row) => (
            <div key={row.name} className="flex flex-col md:flex-row md:items-center gap-3 p-4 rounded-xl hover:bg-zinc-950/60 transition-colors">
              <div className="flex items-center gap-2 min-w-[160px]">
                <StatusDot status={row.status} />
                <span className="text-sm font-semibold text-zinc-100">{row.name}</span>
              </div>
              <p className="text-sm text-zinc-400 leading-6">{row.detail}</p>
            </div>
          ))}
        </div>

        <div className="rounded-2xl border border-amber-900/40 bg-amber-950/20 p-5 text-sm text-amber-300 leading-6">
          {page.note}
        </div>
      </main>
      <GhostFooter />
    </>
  );
}
