{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ai-clock-sync",
    "labels": {
      "app": "ai-clock-sync"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ai-clock-sync"
    },
    "ports": [
      {
        "port": "7690",
        "targetPort": 7690,
        "protocol": "TCP"
      }
    ]
  }
}
