{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ai-monitor",
    "labels": {
      "app": "ai-monitor"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ai-monitor"
    },
    "ports": [
      {
        "port": "7575",
        "targetPort": 7575,
        "protocol": "TCP"
      }
    ]
  }
}
