{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "alerts-service",
    "labels": {
      "app": "alerts-service"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "alerts-service"
    },
    "ports": [
      {
        "port": "7644",
        "targetPort": 7644,
        "protocol": "TCP"
      }
    ]
  }
}
