{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "artifact-server",
    "labels": {
      "app": "artifact-server"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "artifact-server"
    },
    "ports": [
      {
        "port": "8080",
        "targetPort": 80,
        "protocol": "TCP"
      }
    ]
  }
}
