{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "block-index-service",
    "labels": {
      "app": "block-index-service"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "block-index-service"
    },
    "ports": [
      {
        "port": "7626",
        "targetPort": 7626,
        "protocol": "TCP"
      }
    ]
  }
}
