{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "compliance-export-service",
    "labels": {
      "app": "compliance-export-service"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "compliance-export-service"
    },
    "ports": [
      {
        "port": "7621",
        "targetPort": 7621,
        "protocol": "TCP"
      }
    ]
  }
}
