{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ghost-registry",
    "labels": {
      "app": "ghost-registry"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ghost-registry"
    },
    "ports": [
      {
        "port": "18088",
        "targetPort": 8088,
        "protocol": "TCP"
      }
    ]
  }
}
