{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ghostchain-bootnode",
    "labels": {
      "app": "ghostchain-bootnode"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ghostchain-bootnode"
    },
    "ports": [
      {
        "port": "30301",
        "targetPort": 30301,
        "protocol": "UDP"
      }
    ]
  }
}
