{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ghostscout-frontend",
    "labels": {
      "app": "ghostscout-frontend"
    }
  },
  "spec": {
    "type": "LoadBalancer",
    "selector": {
      "app": "ghostscout-frontend"
    },
    "ports": [
      {
        "port": "18640",
        "targetPort": 3000,
        "protocol": "TCP"
      }
    ]
  }
}
