{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ghost-rpc-proxy",
    "labels": {
      "app": "ghost-rpc-proxy"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ghost-rpc-proxy"
    },
    "ports": [
      {
        "port": "8546",
        "targetPort": 8546,
        "protocol": "TCP"
      }
    ]
  }
}
