{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "ghost-guard",
    "labels": {
      "app": "ghost-guard"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "ghost-guard"
    },
    "ports": [
      {
        "port": "7070",
        "targetPort": 7070,
        "protocol": "TCP"
      }
    ]
  }
}
