{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "l2-geth",
    "labels": {
      "app": "l2-geth"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "l2-geth"
    },
    "ports": [
      {
        "port": "29547",
        "targetPort": 8545,
        "protocol": "TCP"
      }
    ]
  }
}
