{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "l3-geth",
    "labels": {
      "app": "l3-geth"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "l3-geth"
    },
    "ports": []
  }
}
