{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "network-context-service",
    "labels": {
      "app": "network-context-service"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "network-context-service"
    },
    "ports": [
      {
        "port": "7633",
        "targetPort": 7633,
        "protocol": "TCP"
      }
    ]
  }
}
