{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "op-proposer",
    "labels": {
      "app": "op-proposer"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "op-proposer"
    },
    "ports": [
      {
        "port": "6062",
        "targetPort": 6060,
        "protocol": "TCP"
      },
      {
        "port": "7302",
        "targetPort": 7300,
        "protocol": "TCP"
      },
      {
        "port": "6546",
        "targetPort": 8545,
        "protocol": "TCP"
      }
    ]
  }
}
