{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "op-sequencer",
    "labels": {
      "app": "op-sequencer"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "op-sequencer"
    },
    "ports": [
      {
        "port": "9646",
        "targetPort": 9646,
        "protocol": "TCP"
      },
      {
        "port": "7303",
        "targetPort": 7303,
        "protocol": "TCP"
      }
    ]
  }
}
