{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "op-supervisor",
    "labels": {
      "app": "op-supervisor"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "op-supervisor"
    },
    "ports": [
      {
        "port": "9045",
        "targetPort": 8545,
        "protocol": "TCP"
      }
    ]
  }
}
