{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "rpc-forward-l1-29545",
    "labels": {
      "app": "rpc-forward-l1-29545"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "rpc-forward-l1-29545"
    },
    "ports": [
      {
        "port": "29545",
        "targetPort": 29545,
        "protocol": "TCP"
      }
    ]
  }
}
