{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "verification-service",
    "labels": {
      "app": "verification-service"
    }
  },
  "spec": {
    "type": "NodePort",
    "selector": {
      "app": "verification-service"
    },
    "ports": [
      {
        "port": "7630",
        "targetPort": 7630,
        "protocol": "TCP"
      }
    ]
  }
}
