-- GSE master schema (TimescaleDB)
-- Applied via docker-entrypoint-initdb.d

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- Nations registry
CREATE TABLE IF NOT EXISTS nations (
    address     CHAR(42)    PRIMARY KEY,
    name        TEXT        NOT NULL,
    iso_code    CHAR(3),
    registered_at TIMESTAMPTZ DEFAULT now()
);

-- GDP records (hypertable)
CREATE TABLE IF NOT EXISTS gdp_records (
    id          BIGSERIAL   NOT NULL,
    nation      CHAR(42)    NOT NULL REFERENCES nations(address),
    value_usd   NUMERIC(30,6) NOT NULL,   -- in billions USD
    currency    CHAR(3)     NOT NULL DEFAULT 'USD',
    period      TEXT        NOT NULL,      -- e.g. '2026-Q1'
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tx_hash     CHAR(66),
    PRIMARY KEY (id, recorded_at)
);
SELECT create_hypertable('gdp_records', 'recorded_at', if_not_exists => TRUE);
CREATE INDEX ON gdp_records (nation, recorded_at DESC);

-- Tax policies
CREATE TABLE IF NOT EXISTS tax_policies (
    nation          CHAR(42)    PRIMARY KEY REFERENCES nations(address),
    income_tax_bps  INTEGER     NOT NULL DEFAULT 0 CHECK (income_tax_bps BETWEEN 0 AND 10000),
    corporate_tax_bps INTEGER   NOT NULL DEFAULT 0 CHECK (corporate_tax_bps BETWEEN 0 AND 10000),
    vat_bps         INTEGER     NOT NULL DEFAULT 0 CHECK (vat_bps BETWEEN 0 AND 10000),
    tariff_bps      INTEGER     NOT NULL DEFAULT 0 CHECK (tariff_bps BETWEEN 0 AND 10000),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

-- Tax collections (hypertable)
CREATE TABLE IF NOT EXISTS tax_collections (
    id          BIGSERIAL   NOT NULL,
    nation      CHAR(42)    NOT NULL,
    payer       CHAR(42)    NOT NULL,
    amount_wei  NUMERIC(40,0) NOT NULL,
    tax_type    TEXT        NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tx_hash     CHAR(66),
    PRIMARY KEY (id, collected_at)
);
SELECT create_hypertable('tax_collections', 'collected_at', if_not_exists => TRUE);

-- Budget allocations
CREATE TABLE IF NOT EXISTS budgets (
    id          BIGSERIAL   PRIMARY KEY,
    nation      CHAR(42)    NOT NULL,
    category    TEXT        NOT NULL,
    amount_wei  NUMERIC(40,0) NOT NULL,
    spent_wei   NUMERIC(40,0) NOT NULL DEFAULT 0,
    description TEXT,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- Trade records (hypertable)
CREATE TABLE IF NOT EXISTS trades (
    id          BIGSERIAL   NOT NULL,
    exporter    CHAR(42)    NOT NULL,
    importer    CHAR(42)    NOT NULL,
    commodity   TEXT        NOT NULL,
    quantity    NUMERIC(30,0),
    value_usd   NUMERIC(20,6),
    tariff_bps  INTEGER,
    status      TEXT        NOT NULL DEFAULT 'pending',
    traded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    tx_hash     CHAR(66),
    PRIMARY KEY (id, traded_at)
);
SELECT create_hypertable('trades', 'traded_at', if_not_exists => TRUE);
CREATE INDEX ON trades (exporter, traded_at DESC);
CREATE INDEX ON trades (importer, traded_at DESC);

-- Infrastructure projects
CREATE TABLE IF NOT EXISTS infra_projects (
    id              BIGSERIAL   PRIMARY KEY,
    name            TEXT        NOT NULL,
    nation          CHAR(42)    NOT NULL,
    target_funding  NUMERIC(40,0) NOT NULL,
    raised          NUMERIC(40,0) NOT NULL DEFAULT 0,
    completion_date TIMESTAMPTZ,
    active          BOOLEAN     NOT NULL DEFAULT TRUE,
    completed       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Infrastructure bonds
CREATE TABLE IF NOT EXISTS infra_bonds (
    id          BIGSERIAL   PRIMARY KEY,
    project_id  BIGINT      NOT NULL REFERENCES infra_projects(id),
    holder      CHAR(42)    NOT NULL,
    principal   NUMERIC(40,0) NOT NULL,
    coupon_bps  INTEGER     NOT NULL,
    issued_at   TIMESTAMPTZ DEFAULT now(),
    redeemed    BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Economic alerts (generated by gse-ai)
CREATE TABLE IF NOT EXISTS economic_alerts (
    id          BIGSERIAL   PRIMARY KEY,
    alert_type  TEXT        NOT NULL,
    severity    TEXT        NOT NULL DEFAULT 'info',
    message     TEXT        NOT NULL,
    data        JSONB,
    created_at  TIMESTAMPTZ DEFAULT now(),
    resolved_at TIMESTAMPTZ
);
