#!/usr/bin/env bash
# scripts/deploy-ghostx.sh
# ─────────────────────────────────────────────────────────────────
# Deploy the Ghost X smart contracts to GhostChain L2
# and write the resulting addresses to .env.ghostx.
#
# Usage:
#   DEPLOYER_PRIVATE_KEY=0x…  TREASURY=0x…  bash scripts/deploy-ghostx.sh
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS_DIR="$REPO_DIR/contracts"
DEPLOY_OUT="$CONTRACTS_DIR/deployments/ghostx-l2.json"

L2_RPC_URL="${L2_RPC_URL:-http://localhost:8547}"
DEPLOYER="${DEPLOYER:-$(cast wallet address "$DEPLOYER_PRIVATE_KEY")}"
TREASURY="${TREASURY:?TREASURY env var required}"
STAKE_TOKEN="${STAKE_TOKEN:?STAKE_TOKEN env var required (GST or governance token address)}"

echo "╔═══════════════════════════╗"
echo "║   Ghost X – Deploy L2     ║"
echo "╚═══════════════════════════╝"
echo "  RPC      : $L2_RPC_URL"
echo "  Deployer : $DEPLOYER"
echo "  Treasury : $TREASURY"
echo "  StakeToken: $STAKE_TOKEN"
echo

cd "$CONTRACTS_DIR"

forge script script/DeployGhostX.s.sol \
    --rpc-url   "$L2_RPC_URL"           \
    --broadcast                          \
    --sender    "$DEPLOYER"              \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    -vvv

if [[ ! -f "$DEPLOY_OUT" ]]; then
    echo "ERROR: $DEPLOY_OUT not found. Did the deployment fail?"
    exit 1
fi

# ── Parse addresses ────────────────────────────────────────────────────────────
FEE_COLLECTOR=$(jq -r '.feeCollector' "$DEPLOY_OUT")
VAULT=$(jq -r         '.vault'        "$DEPLOY_OUT")
ORDER_BOOK=$(jq -r    '.orderBook'    "$DEPLOY_OUT")
BADGE=$(jq -r         '.badge'        "$DEPLOY_OUT")
STAKING=$(jq -r       '.staking'      "$DEPLOY_OUT")

echo
echo "✔ Deployed:"
echo "  FeeCollector : $FEE_COLLECTOR"
echo "  Vault        : $VAULT"
echo "  OrderBook    : $ORDER_BOOK"
echo "  Badge        : $BADGE"
echo "  Staking      : $STAKING"

# ── Write/update .env.ghostx ───────────────────────────────────────────────────
ENV_FILE="$REPO_DIR/.env.ghostx"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/deploy-ghostx.sh – $(date -u +"%Y-%m-%dT%H:%M:%SZ")
GHOSTX_FEE_COLLECTOR=$FEE_COLLECTOR
GHOSTX_VAULT=$VAULT
GHOSTX_ORDER_BOOK=$ORDER_BOOK
GHOSTX_BADGE=$BADGE
GHOSTX_STAKING=$STAKING
GHOSTX_STAKE_TOKEN=$STAKE_TOKEN
L2_RPC_URL=$L2_RPC_URL
TREASURY=$TREASURY
EOF

echo
echo "✔ Addresses written to $ENV_FILE"
echo "  → Copy into services/ghostx-api/.env and apps/ghostx/.env before starting Docker."
