#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# GhostChain — Master Production Deployment Script
#
# Idempotent — safe to run multiple times. Each step checks whether it has
# already been applied and skips if so.
#
# Usage:
#   sudo bash scripts/deploy-production.sh [--skip-netplan] [--skip-ssl]
#                                           [--skip-build]  [--dry-run]
#
# Run from the workspace root:
#   cd /home/ghost/ghostl-stack
#   sudo bash scripts/deploy-production.sh
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NGINX_CONF_SRC="${WORKSPACE_ROOT}/infra/nginx"
NGINX_CONF_DST="/etc/nginx"
NETPLAN_SRC="${WORKSPACE_ROOT}/infra/network/netplan-ghostchain.yaml"
NETPLAN_DST="/etc/netplan/01-network.yaml"
WEB_DIR="${WORKSPACE_ROOT}/apps/web"
NODE_BIN="$(command -v node || echo /usr/bin/node)"
PM2_BIN="$(command -v pm2 || echo "")"

SKIP_NETPLAN=false
SKIP_SSL=false
SKIP_BUILD=false
DRY_RUN=false

# ── Argument handling ─────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --skip-netplan) SKIP_NETPLAN=true ;;
    --skip-ssl)     SKIP_SSL=true     ;;
    --skip-build)   SKIP_BUILD=true   ;;
    --dry-run)      DRY_RUN=true      ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[deploy] $(date '+%H:%M:%S')  $*"; }
warn() { echo "[deploy] WARN   $*" >&2; }
die()  { echo "[deploy] ERROR  $*" >&2; exit 1; }
run()  {
  if [[ "${DRY_RUN}" == "true" ]]; then
    echo "[deploy] [DRY-RUN] would run: $*"
  else
    "$@"
  fi
}

separator() {
  log "────────────────────────────────────────────────────────────"
}

# ── Privilege check ───────────────────────────────────────────────────────────
[[ "$EUID" -ne 0 ]] && die "Must be run as root (sudo bash $0)"

cd "${WORKSPACE_ROOT}"
log "GhostChain Production Deployment"
log "Workspace: ${WORKSPACE_ROOT}"
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Install system packages
# ─────────────────────────────────────────────────────────────────────────────
log "[1/7] Installing system packages (nginx, certbot)..."
run apt-get update -qq
run apt-get install -y -qq nginx certbot python3-certbot-nginx
log "      nginx: $(nginx -v 2>&1 || echo 'installed')"
log "      certbot: $(certbot --version 2>&1 || echo 'installed')"
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Apply netplan (add IP addresses)
# ─────────────────────────────────────────────────────────────────────────────
if [[ "${SKIP_NETPLAN}" == "true" ]]; then
  log "[2/7] Netplan: SKIPPED (--skip-netplan)"
else
  log "[2/7] Applying netplan config (adds 6 additional IP aliases)..."
  if [[ ! -f "${NETPLAN_SRC}" ]]; then
    die "Netplan source not found: ${NETPLAN_SRC}"
  fi
  run cp "${NETPLAN_SRC}" "${NETPLAN_DST}"
  run chmod 600 "${NETPLAN_DST}"
  run netplan apply
  log "      Netplan applied. IPs active:"
  ip addr show enp1s0 | grep "inet " | awk '{print "         ", $2}' || true
fi
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Install nginx config
# ─────────────────────────────────────────────────────────────────────────────
log "[3/7] Installing nginx configuration..."

# nginx.conf
run cp "${NGINX_CONF_SRC}/nginx.conf" "${NGINX_CONF_DST}/nginx.conf"

# Snippets
run mkdir -p "${NGINX_CONF_DST}/snippets"
run cp "${NGINX_CONF_SRC}/snippets/"*.conf "${NGINX_CONF_DST}/snippets/"

# Virtual hosts
run mkdir -p "${NGINX_CONF_DST}/sites-available" "${NGINX_CONF_DST}/sites-enabled"
for conf in "${NGINX_CONF_SRC}/sites-available/"*.conf; do
  name="$(basename "${conf}")"
  run cp "${conf}" "${NGINX_CONF_DST}/sites-available/${name}"
  run ln -sf "${NGINX_CONF_DST}/sites-available/${name}" \
              "${NGINX_CONF_DST}/sites-enabled/${name}"
done

# ACME webroot
run mkdir -p /var/www/letsencrypt

# SSL dir (DH params generated by ssl-init.sh)
run mkdir -p "${NGINX_CONF_DST}/ssl"

# Test nginx config with HTTP-only server blocks (no SSL certs yet)
# Temporarily disable HTTPS server blocks for first-pass syntax test
log "      Validating nginx config (pre-SSL)..."
run nginx -t || warn "nginx -t failed — check config before proceeding"

# Start (or reload) nginx — HTTP only at this point
if systemctl is-active --quiet nginx; then
  log "      Reloading nginx..."
  run nginx -t && run systemctl reload nginx
else
  log "      Starting nginx..."
  run systemctl enable nginx
  run systemctl start nginx
fi
log "      nginx is running (HTTP-only, serving ACME challenge path)"
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — SSL / Let's Encrypt
# ─────────────────────────────────────────────────────────────────────────────
if [[ "${SKIP_SSL}" == "true" ]]; then
  log "[4/7] SSL: SKIPPED (--skip-ssl)"
else
  log "[4/7] Running SSL initialization..."
  run bash "${WORKSPACE_ROOT}/scripts/ssl-init.sh"
fi
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — Final nginx reload with HTTPS
# ─────────────────────────────────────────────────────────────────────────────
log "[5/7] Reloading nginx with HTTPS virtual hosts..."
run nginx -t && run systemctl reload nginx
log "      nginx online with TLS."
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Build Next.js portal
# ─────────────────────────────────────────────────────────────────────────────
if [[ "${SKIP_BUILD}" == "true" ]]; then
  log "[6/7] Next.js build: SKIPPED (--skip-build)"
else
  log "[6/7] Building Next.js portal..."
  # Switch to real user if sudo'd, to avoid building as root
  REAL_USER="${SUDO_USER:-root}"
  if [[ "${DRY_RUN}" == "false" ]]; then
    sudo -u "${REAL_USER}" bash -c \
      "cd '${WEB_DIR}' && NODE_ENV=production npm run build" \
      || die "Next.js build failed"
  else
    log "      [DRY-RUN] would run: npm run build in ${WEB_DIR}"
  fi
  log "      Build complete: ${WEB_DIR}/.next-ghost/standalone"
fi
separator

# ─────────────────────────────────────────────────────────────────────────────
# STEP 7 — Start / restart portal process
# ─────────────────────────────────────────────────────────────────────────────
log "[7/7] Starting portal process..."
STANDALONE_SERVER="${WEB_DIR}/.next-ghost/standalone/server.js"

if [[ ! -f "${STANDALONE_SERVER}" && "${DRY_RUN}" == "false" && "${SKIP_BUILD}" == "false" ]]; then
  warn "Standalone server not found at ${STANDALONE_SERVER}"
  warn "Next.js build may not have produced a standalone output."
  warn "Check apps/web/next.config.js: output: 'standalone'"
fi

REAL_USER="${SUDO_USER:-ghost}"

if command -v pm2 &>/dev/null; then
  log "      Using PM2 process manager..."
  run sudo -u "${REAL_USER}" pm2 describe ghostchain-portal &>/dev/null \
    && run sudo -u "${REAL_USER}" pm2 restart ghostchain-portal \
    || run sudo -u "${REAL_USER}" pm2 start "${STANDALONE_SERVER}" \
         --name ghostchain-portal \
         --interpreter "${NODE_BIN}" \
         --env production \
         -- PORT=3200 HOSTNAME=0.0.0.0
  run sudo -u "${REAL_USER}" pm2 save
  # Enable PM2 startup on boot
  PM2_STARTUP="$(sudo -u "${REAL_USER}" pm2 startup --no-daemon 2>&1 | tail -1 || true)"
  log "      PM2 startup: ${PM2_STARTUP}"
else
  log "      PM2 not found — install with: npm install -g pm2"
  log "      Then re-run this step or start manually:"
  log "        PORT=3200 HOSTNAME=0.0.0.0 node ${STANDALONE_SERVER}"
fi
separator

# ── Summary ───────────────────────────────────────────────────────────────────
log ""
log "════════════════════════════════════════════════════════════"
log "  GhostChain Production Deployment Complete"
[[ "${DRY_RUN}" == "true" ]] && log "  ⚠  Mode: DRY RUN — no system changes made"
log ""
log "  Active domains:"
log "    https://ghostchain.cloud    — Primary portal"
log "    https://ghostchain.info     — GhostChain info"
log "    https://ghostchain.life     — Live chain data"
log "    https://ghostchain.live     — Live chain data (alias)"
log "    https://ghostchain.online   — Online portal"
log "    https://ghostchain.space    — GhostBrain AI"
log "    https://ghostchain.store    — GhostXchange DEX"
log "    https://ghostchain.world    — World portal"
log "    https://ghostchainlink.com  — Bridge portal"
log "    https://ghostschain.com     — Bridge portal (alias)"
log "    https://ghostchainsolutions.com — Enterprise"
log ""
log "  API:  https://api.ghostchain.cloud"
log "  Portal internal: http://127.0.0.1:3200"
log "  API internal:    http://127.0.0.1:4000"
log ""
log "  Logs:"
log "    nginx:   journalctl -u nginx -f"
log "    portal:  pm2 logs ghostchain-portal"
log "════════════════════════════════════════════════════════════"
