// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

// ╔══════════════════════════════════════════════════════════════════════════╗
// ║          GhostChain · GhostBrain AI Contract Evolution System           ║
// ║  Self-learning · Self-evolving · Autonomous · GhostStack v2             ║
// ╚══════════════════════════════════════════════════════════════════════════╝

/// @title  GhostBrainEvolutionLedger
/// @notice Append-only ledger that records every AI learning cycle, model
///         version bump, and contract evolution event for GhostBrain Core.
///         The ledger is the authoritative source-of-truth for reproduced
///         AI decisions on the GhostChain L1.
///
/// @dev    Routing law: this contract lives on L1 and is written to only by
///         the GhostBrainOracle (an L1-resident AI attestor).  L2/L3 AI
///         nodes publish to this ledger via the standard L2→L1 messenger;
///         direct L3→L1 writes are blocked by the routing guard modifier.
contract GhostBrainEvolutionLedger {

    // ─── Roles ────────────────────────────────────────────────────────────

    bytes32 public constant ORACLE_ROLE = keccak256("ORACLE_ROLE");
    bytes32 public constant ADMIN_ROLE  = keccak256("ADMIN_ROLE");

    mapping(bytes32 => mapping(address => bool)) private _roles;

    // ─── Types ────────────────────────────────────────────────────────────

    enum EvolutionKind {
        MODEL_VERSION_BUMP,     // AI model updated (weights/config)
        CONTRACT_CREATED,       // new contract auto-generated by AI
        CONTRACT_UPGRADED,      // existing contract auto-upgraded
        ERROR_FIXED,            // AI applied an automatic bug-fix
        COMPILE_SUCCESS,        // autonomous compile cycle succeeded
        COMPILE_FAILURE,        // autonomous compile cycle failed
        LEARNING_CYCLE,         // periodic self-training epoch
        POLICY_UPDATED          // AI policy hash changed
    }

    struct EvolutionRecord {
        uint64  id;
        EvolutionKind kind;
        /// @dev target contract address (zero if N/A)
        address target;
        uint256 chainId;
        /// @dev keccak256 of the new source/bytecode/model artifact
        bytes32 artifactHash;
        /// @dev previous artifact hash (for upgrade diff)
        bytes32 prevArtifactHash;
        /// @dev IPFS CID or off-chain URI where full artifact is stored
        bytes   storageUri;
        /// @dev AI confidence score: 0–10 000 bps (10 000 = 100%)
        uint16  confidenceBps;
        /// @dev freeform label for the cycle
        bytes32 label;
        address oracle;
        uint256 timestamp;
        uint256 blockNumber;
    }

    uint64 public recordCount;
    mapping(uint64 => EvolutionRecord) public records;

    /// @dev latest record id for a (chainId, target) pair
    mapping(uint256 => mapping(address => uint64)) public latestRecordFor;
    /// @dev model version counter (incremented on MODEL_VERSION_BUMP)
    uint64 public modelVersion;

    // ─── Events ───────────────────────────────────────────────────────────

    event EvolutionRecorded(
        uint64  indexed id,
        EvolutionKind   kind,
        address indexed target,
        uint256         chainId,
        bytes32         artifactHash,
        uint16          confidenceBps,
        address indexed oracle
    );

    event ModelVersionBumped(uint64 newVersion, bytes32 artifactHash, address by);

    // ─── Errors ───────────────────────────────────────────────────────────

    error Unauthorized();
    error InvalidConfidence();
    error ZeroArtifact();

    // ─── Constructor ──────────────────────────────────────────────────────

    constructor(address admin_) {
        _grantRole(ADMIN_ROLE, admin_);
        _grantRole(ORACLE_ROLE, admin_);
    }

    // ─── Access control ───────────────────────────────────────────────────

    modifier onlyRole(bytes32 role) {
        if (!_roles[role][msg.sender]) revert Unauthorized();
        _;
    }

    function grantRole(bytes32 role, address account) external onlyRole(ADMIN_ROLE) {
        _grantRole(role, account);
    }

    function revokeRole(bytes32 role, address account) external onlyRole(ADMIN_ROLE) {
        _roles[role][account] = false;
    }

    function hasRole(bytes32 role, address account) external view returns (bool) {
        return _roles[role][account];
    }

    // ─── Core: record evolution ───────────────────────────────────────────

    /// @notice Record an AI evolution event.
    /// @param kind           What kind of evolution happened.
    /// @param target         Contract that was created/fixed/upgraded (zero if N/A).
    /// @param chainId        Chain where the target lives.
    /// @param artifactHash   Hash of the new artifact.
    /// @param prevArtifact   Hash of the artifact being replaced (zero for new).
    /// @param storageUri     Off-chain storage reference.
    /// @param confidenceBps  AI confidence 0–10 000.
    /// @param label          Short human-readable label.
    function record(
        EvolutionKind kind,
        address       target,
        uint256       chainId,
        bytes32       artifactHash,
        bytes32       prevArtifact,
        bytes calldata storageUri,
        uint16        confidenceBps,
        bytes32       label
    ) external onlyRole(ORACLE_ROLE) returns (uint64 id) {
        if (confidenceBps > 10_000) revert InvalidConfidence();
        if (artifactHash == bytes32(0)) revert ZeroArtifact();

        unchecked { id = ++recordCount; }

        records[id] = EvolutionRecord({
            id:               id,
            kind:             kind,
            target:           target,
            chainId:          chainId,
            artifactHash:     artifactHash,
            prevArtifactHash: prevArtifact,
            storageUri:       storageUri,
            confidenceBps:    confidenceBps,
            label:            label,
            oracle:           msg.sender,
            timestamp:        block.timestamp,
            blockNumber:      block.number
        });

        if (target != address(0)) {
            latestRecordFor[chainId][target] = id;
        }

        if (kind == EvolutionKind.MODEL_VERSION_BUMP) {
            unchecked { ++modelVersion; }
            emit ModelVersionBumped(modelVersion, artifactHash, msg.sender);
        }

        emit EvolutionRecorded(id, kind, target, chainId, artifactHash, confidenceBps, msg.sender);
    }

    // ─── Views ────────────────────────────────────────────────────────────

    function getRecord(uint64 id) external view returns (EvolutionRecord memory) {
        return records[id];
    }

    /// @notice Return the last N records (newest first).
    function tail(uint64 n) external view returns (EvolutionRecord[] memory out) {
        uint64 total = recordCount;
        if (n > total) n = total;
        out = new EvolutionRecord[](n);
        for (uint64 i = 0; i < n; ) {
            out[i] = records[total - i];
            unchecked { ++i; }
        }
    }

    // ─── Internal ─────────────────────────────────────────────────────────

    function _grantRole(bytes32 role, address account) internal {
        _roles[role][account] = true;
    }
}
