flush ruleset

table inet ghostnetsync {
  chain input {
    type filter hook input priority 0;
    policy drop;
    iif "lo" accept
    ct state established,related accept
    tcp dport {22,8099} accept
  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;
    ct state established,related accept
    iifname "br-l3" oifname "br-l2" accept
    iifname "br-l2" oifname "br-l1" accept
    iifname "br-l3" oifname != "br-l2" drop
    iifname "br-l2" oifname != "br-l1" drop
    iifname "br-l1" accept
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}
