[ghostdns-named]
enabled  = true
port     = 53
protocol = udp
filter   = ghostdns-named
logpath  = /var/log/named/named.log
maxretry = 20
findtime = 60
bantime  = 600
action   = iptables-multiport[name=ghostdns-named, port="53", protocol=udp]
